//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventEntites : DbContext
    {
        public EventEntites()
            : base("name=EventEntites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<EventParticipatns> EventParticipatns { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Participants> Participants { get; set; }
    }
}
