INSERT INTO dbo.Cities VALUES ('Grad1')
INSERT INTO dbo.Cities VALUES ('Grad2')
INSERT INTO dbo.Cities VALUES ('Grad3')
------------------------------------------------------------------------------
INSERT INTO dbo.Participants VALUES ( 'Ime1', 'Prezime1', 'Adresa1', 1)	
INSERT INTO dbo.Participants VALUES ( 'Ime2', 'Prezime2', 'Adresa2', 2)	
INSERT INTO dbo.Participants VALUES ( 'Ime3', 'Prezime3', 'Adresa3', 3)
INSERT INTO dbo.Participants VALUES ( 'Ime4', 'Prezime4', 'Adresa4', 1)
INSERT INTO dbo.Participants VALUES ( 'Ime5', 'Prezime5', 'Adresa5', 2)
INSERT INTO dbo.Participants VALUES ( 'Ime6', 'Prezime6', 'Adresa6', 3)
INSERT INTO dbo.Participants VALUES ( 'Ime7', 'Prezime7', 'Adresa7', 1)
INSERT INTO dbo.Participants VALUES ( 'Ime8', 'Prezime8', 'Adresa8', 2)
INSERT INTO dbo.Participants VALUES ( 'Ime9', 'Prezime9', 'Adresa9', 3)
------------------------------------------------------------------------------
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije1', 'AdresaLokacije1', 1)
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije2', 'AdresaLokacije2', 2)
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije3', 'AdresaLokacije3', 3)
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije4', 'AdresaLokacije4', 1)
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije5', 'AdresaLokacije5', 2)
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije6', 'AdresaLokacije6', 3)
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije7', 'AdresaLokacije7', 1)
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije8', 'AdresaLokacije8', 2)
INSERT INTO dbo.Locations VALUES ( 'ImeLokacije9', 'AdresaLokacije9', 3)
------------------------------------------------------------------------------
INSERT INTO dbo.Events VALUES ( 'ImeEventa1', 0, '2020-6-6', '2020-6-20', 1)
INSERT INTO dbo.Events VALUES ( 'ImeEventa2', 0, '2020-6-6', '2020-6-20', 2)
INSERT INTO dbo.Events VALUES ( 'ImeEventa3', 0, '2020-6-6', '2020-6-20', 3)
INSERT INTO dbo.Events VALUES ( 'ImeEventa4', 0, '2020-6-6', '2020-6-20', 1)
INSERT INTO dbo.Events VALUES ( 'ImeEventa5', 0, '2020-6-6', '2020-6-20', 2)
INSERT INTO dbo.Events VALUES ( 'ImeEventa6', 0, '2020-6-6', '2020-6-20', 3)
INSERT INTO dbo.Events VALUES ( 'ImeEventa7', 0, '2020-6-6', '2020-6-20', 1)
INSERT INTO dbo.Events VALUES ( 'ImeEventa8', 0, '2020-6-6', '2020-6-20', 2)
INSERT INTO dbo.Events VALUES ( 'ImeEventa9', 0, '2020-6-6', '2020-6-20', 3)
------------------------------------------------------------------------------
INSERT INTO dbo.EventParticipatns VALUES (1, 1)
INSERT INTO dbo.EventParticipatns VALUES (2, 2)
INSERT INTO dbo.EventParticipatns VALUES (3, 3)
INSERT INTO dbo.EventParticipatns VALUES (1, 4)
INSERT INTO dbo.EventParticipatns VALUES (2, 5)
INSERT INTO dbo.EventParticipatns VALUES (3, 6)
INSERT INTO dbo.EventParticipatns VALUES (1, 7)
INSERT INTO dbo.EventParticipatns VALUES (2, 8)
INSERT INTO dbo.EventParticipatns VALUES (3, 9)
INSERT INTO dbo.EventParticipatns VALUES ( 1, 1)
INSERT INTO dbo.EventParticipatns VALUES ( 2, 2)
INSERT INTO dbo.EventParticipatns VALUES ( 3, 3)